// <auto-generated />
using System;
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datos.Migrations
{
    [DbContext(typeof(ProductosContext))]
    partial class ProductosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entity.Producto", b =>
                {
                    b.Property<string>("CodigoP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CantidadP")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fechadevencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("LaboratorioP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoP");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Entity.Venta", b =>
                {
                    b.Property<string>("ProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CantidadV")
                        .HasColumnType("int");

                    b.Property<string>("CodigoV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fechadeventa")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrecioV")
                        .HasColumnType("int");

                    b.Property<string>("ProductoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalV")
                        .HasColumnType("int");

                    b.HasKey("ProductoId");

                    b.ToTable("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
